// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhoDFtf_a29OmceTh7PbLgRxei8RUk_d8',
    appId: '1:925288025067:web:16c81437be2fac75a527ae',
    messagingSenderId: '925288025067',
    projectId: 'roka-hackathon',
    authDomain: 'roka-hackathon.firebaseapp.com',
    storageBucket: 'roka-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd4g4iB8xX8OL6pcbrEEwUvg1MrWNEuR0',
    appId: '1:925288025067:android:f9e520dc259f0842a527ae',
    messagingSenderId: '925288025067',
    projectId: 'roka-hackathon',
    storageBucket: 'roka-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcHXxZs1R1BwuR-B0hf7ykt2LFnrf0Scc',
    appId: '1:925288025067:ios:9c3d0b4cf9183c53a527ae',
    messagingSenderId: '925288025067',
    projectId: 'roka-hackathon',
    storageBucket: 'roka-hackathon.firebasestorage.app',
    iosBundleId: 'com.example.defenseInventory',
  );
}
